### ISSUE TITLE
Implement Simple Subscription Service

### ISSUE THREAD

**Issue by JavaSaBr** [JavaSaBr/mqtt-broker#1]
1. Create an interface SubscriptionService with methods:
 1.subscribe(mqttClient, topic)
 2.unsubscribe(mqttClient, topic)
 3.getSubscribers(topic)
2. Create s very simple implementation based on hash map with name SimpleSubscriptionService

**Comment by JavaSaBr** [comment]
Topic is SubscribeTopicFilter class

**Comment by crazyrokr** [comment]
Done
